#!/bin/bash

tractography ()
{

# Start clock
START=$(date +%s.%N)
echo "****** Processing Tractography (VTK) " $SUBJ... " ******"
echo "[$SUBJ-1/30] Output Directory ready!"

# ------------- Diffusion Tensor Imaging --------------------------
echo "[$SUBJ-23/30] Cutting hairs less than 40..."
cat $work_dir/$tractography_image | procstreamlines -mintractlength 40 -waypointfile $work_dir/seed3.nii.gz -header $work_dir/seed3.nii.gz -exclusionfile $work_dir/brain2_mask_diff.nii.gz -truncateinexclusion > $work_dir/tracks3.camino
echo "[$SUBJ-23/30] Hairs gone..."

# Generate VTK files to visualize
echo "[$SUBJ-24/30] Exporting streamlines to VTK polydata..."
vtkstreamlines -colourorient < $work_dir/tracks3.camino > $work_dir/$VTK_image
echo "[$SUBJ-24/30] Export Done!"

# Calculate elapsed time
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "Elapsed Time: " $DIFF " Secs."

echo "***** Tractography " $SUBJ" Done! *****"

}

kmc_400_root=/media/DATAPART5/kmc400
apps_root=/media/DATAPART5/applications

# Code of the subject (first parameter of the script)
SUBJ=$1
# Convert images from Dicom to Nifti?
convert_images=false
# Camino bin directory
camino_bin=$apps_root/camino/bin
# FSL bin directory
fsl_bin=$apps_root/fsl/fsl/bin
# dcm2nii directory
dcm2nii_path=$apps_root/mricron
#Export applications PATH
export PATH=$PATH:$camino_bin:$fsl_bin:$dcm2nii_path

# Original anatomic image
original_file_image=orig
# Seed file
seed_file_image=brain # Whole brain
# Directory of Dicom Images
dicom_repo=/media/DATAPART5/Dicom
# Freesurfer path (segmented files)
freesurfer_path=$kmc_400_root/freeSurfer_Tracula
# Already converted images to nifti directory
nifti_already_converted=$kmc_400_root/nii
# Input directory
in_dir=$nifti_already_converted/$SUBJ
# Output directory
work_dir=$kmc_400_root/tractography_w_cerebellum/$SUBJ
# Dcm2nii configuration file
dcm2nii_conf=dcm2nii_kmc.ini
# Anatomic image file
anatomic_image_file=MPRAGEmodifiedSENSE.nii.gz
# bvec file
bvec_file=xDTIhighisoSENSE.bvec
# bval file
bval_file=xDTIhighisoSENSE.bval
# DTI image file
dti_image_file=xDTIhighisoSENSE.nii.gz
# scheme file
scheme_file=scheme.txt
# scheme file scale
schemeScale=1.25
# DWI image file 
dwi_image_file=dwi.Bfloat
# Difusion Tensor Image
difusion_tensor_image=dt.Bdouble
# Eigen system Difusion Tensor Image
dt_eigen_image=dteig.Bdouble
# First Brain mask
brain_mask=brain1.nii.gz
# First Binary Brain Mask (generated by bet)
binary_brain_mask=brain1_mask.nii.gz
# Second Brain mask
brain2_mask=brain2.nii.gz
# Second Binary Brain Mask (generated by bet)
binary_brain2_mask=brain2_mask.nii.gz
# Camino tractography outpu file
tractography_image=CaminoTracts.Bfloat
# Tracts in VTK format
VTK_image=CaminoTracts.vtk

# Check if there is more than one parameter 
if [ $# -lt 1 ]
then
echo Usage: $0 subject
exit 0
fi


# Set up output to console and log file (at the same time)
exec 3>&1 1>>$work_dir/log.txt 2>&1

# Call the tractography function. Send the stdout and stderr to log file
tractography | tee /dev/fd/3

